fby3: fix sol-util 2ou bic I2C error (#1184)
Summary:
BMC send I2C set command to cpld for select UART path when sol-util select 2ou.
But there is no need for SierraPoint.
The cpld address does not exist to cause I2C write/read error.
Remove I2C set command to cpld for SierraPoint.

Pull Request resolved: https://github.com/facebookexternal/openbmc.wiwynn/pull/1184

Test Plan:
Build and test PASS on fby3 system with 2OU (SPE and M.2 board)
1. sol-util select 2ou bic
root@bmc-oob:~# sol-util slot1 2ou bic

------------------TERMINAL MULTIPLEXER---------------------
  CTRL-l ?   : Display help message.
  CTRL-l x : Terminate the connection.
  /var/log/mTerm_slot1.log : Log location
  CTRL-l + b : Send Break

-----------------------------------------------------------

Bad command!

>

Reviewed By: zhdaniel12

fbshipit-source-id: d6918372ac

diff --git a/meta-facebook/meta-fby3/recipes-fby3/plat-utils/files/ast-functions b/meta-facebook/meta-fby3/recipes-fby3/plat-utils/files/ast-functions
--- a/meta-facebook/meta-fby3/recipes-fby3/plat-utils/files/ast-functions
+++ b/meta-facebook/meta-fby3/recipes-fby3/plat-utils/files/ast-functions
@@ -441,3 +441,17 @@ is_date_synced() {
     echo 0
   fi
 }
+
+# Get 2OU board type
+# M.2 board: 0x01
+# E1.S board: 0x02
+function get_2ou_board_type() {
+  local bus=$1
+  type=$(/usr/sbin/i2cget -y $bus $SB_CPLD_ADDR 0xD)
+  if [ $? -ne 0 ]; then
+    # if get board type fail, return M.2 board as default
+    echo "0x01"
+  else
+    echo $type
+  fi
+}
