Take RPU number instead of uniqueDeviceAddress in RPU ready command
Summary:
Use the helper script and config to take the RPU number when
running the RPU ready command

Test Plan:
Tested the script on an RMC
Good case - working RPU 1
```
# /usr/libexec/rpu-controller/rpu-ready 1
{"status": "success", "ready": false}
```
Bad case - disconnected RPU 3
```
root@rmc018-oob:~# /usr/libexec/rpu-controller/rpu-ready 3
{"message": "Rackmon output: ERR_INVALID_ARGS", "status": "error"}
```
Bad case - missing RPU mapping
```
root@rmc018-oob:~# /usr/libexec/rpu-controller/rpu-ready 4
Could not determine RPU unique device address
```

Rollback Plan:

Reviewed By: amithash

Differential Revision: D77964310

fbshipit-source-id: a536a5335a3f6894850a8e13d5ef5365b499bdfb

diff --git a/common/recipes-core/rpu-controller/files/rpu-ready b/common/recipes-core/rpu-controller/files/rpu-ready
--- a/common/recipes-core/rpu-controller/files/rpu-ready
+++ b/common/recipes-core/rpu-controller/files/rpu-ready
@@ -1,18 +1,32 @@
 #!/bin/bash
 
 # ARGUMENTS:
-# 1: Unique Dev Address
+# 1: RPU Number
+# 2: Optional override config
 
-if [ $# -ne 1 ]; then
-    echo "Usage: $0 <unique_device_address>
-      unique_device_address: The address of the RPU modbus device to check if ready"
+if [ $# -lt 1 ]; then
+    echo "Usage: $0 <rpu_number> [override_config]
+      rpu_number: The RPU number
+      override_config: Optional configuration file to override default settings in
+                       /usr/share/rpu-controller/config.json"
     exit 1
 fi
 
 set -u
 
+OVERRIDE_CONFIG_FILE=${2:-/usr/share/rpu-controller/config.json}
+CONFIG_FILE="/var/lib/rpu-controller/default-config.json"
+
+if [ -f "$OVERRIDE_CONFIG_FILE" ]; then
+    CONFIG_FILE="$OVERRIDE_CONFIG_FILE"
+fi
+
+script_dir=$( dirname "${BASH_SOURCE[0]}" )
 # unique device address
-UDA="$1"
+UDA=$("$script_dir/get-rpu-unique-device-address" "$1" "$CONFIG_FILE") || {
+  echo "Could not determine RPU unique device address"
+  exit 1
+}
 
 aalcStatusAlarmRegister=37377
 
