GTA: Support SOL-UTIL to CXL
Summary:
# Description
 - As title

 # Motivation
 - Support SOL-UTIL to CXL

 # Test Plan
 - SOL-UTIL to CXL and can send command - pass

 Log:
 ```
 root@bmc-oob:~# sol-util mc cxl1
------------------TERMINAL MULTIPLEXER--------------------- CTRL + x : Terminate the connection.
Run in single mode
-----------------------------------------------------------

0x00000000:0001>fw_ver
Device ID: 0x8702  Rev: 0x01
FW Version: 02.000.011.00
DDR Type: 4
Git Info
  Branch: develop
  Commit: 1cbd786b012c4d5c7d440a6f0e9cb84084b42c71
  Tag: 02.000.011.00
Jun  5 2023 14:57:21
0x00000000:0001>root@bmc-oob:~#
root@bmc-oob:~# sol-util mc cxl2
------------------TERMINAL MULTIPLEXER--------------------- CTRL + x : Terminate the connection.
Run in single mode
-----------------------------------------------------------

0x00000000:0001>
0x00000000:0001>root@bmc-oob:~#
root@bmc-oob:~# sol-util mc cxl3
------------------TERMINAL MULTIPLEXER--------------------- CTRL + x : Terminate the connection.
Run in single mode
-----------------------------------------------------------

0x00000000:0001>
0x00000000:0001>root@bmc-oob:~# sol-util mc cxl4
------------------TERMINAL MULTIPLEXER--------------------- CTRL + x : Terminate the connection.
Run in single mode
-----------------------------------------------------------

0x00000000:0001>
0x00000000:0001>root@bmc-oob:~# sol-util mc cxl5
------------------TERMINAL MULTIPLEXER--------------------- CTRL + x : Terminate the connection.
Run in single mode
-----------------------------------------------------------

0x00000000:0001>
0x00000000:0001>root@bmc-oob:~# sol-util mc cxl6
------------------TERMINAL MULTIPLEXER--------------------- CTRL + x : Terminate the connection.
Run in single mode
-----------------------------------------------------------

0x00000000:0001>
0x00000000:0001>root@bmc-oob:~# sol-util mc cxl7
------------------TERMINAL MULTIPLEXER--------------------- CTRL + x : Terminate the connection.
Run in single mode
-----------------------------------------------------------

0x00000000:0001>
0x00000000:0001>root@bmc-oob:~# sol-util mc cxl8
------------------TERMINAL MULTIPLEXER--------------------- CTRL + x : Terminate the connection.
Run in single mode
-----------------------------------------------------------

0x00000000:0001>
0x00000000:0001>root@bmc-oob:~# sol-util
Usage: sol-util [ mb | cb | mc | cb_pesw0 | cb_pesw1 ]
       sol-util [ cb_accl[1..12]_[1..2] ] uart[0..3] (baudrate)
       sol-util mc [cxl1 | cxl2 ... cxl8] (baudrate)
       sol-util [ mb | cb | mc ] --history
       e.g. sol-util cb_accl1_1 uart0
       e.g. sol-util mc cxl1
root@bmc-oob:~#
 ```

# Description

Please include a summary of the change and which issue is fixed.

# Motivation

Please include an explanation of why you these changes are necessary

X-link: https://github.com/facebookexternal/openbmc.wiwynn/pull/2681

Test Plan: Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

Reviewed By: jagpalgill

Differential Revision: D46854457

fbshipit-source-id: 82aab0f5dac806a1c9bc742eecc0bdeccfc9358e

diff --git a/meta-facebook/meta-grandteton/meta-gtartemis/recipes-gtartemis/plat-utils/files/sol-util b/meta-facebook/meta-grandteton/meta-gtartemis/recipes-gtartemis/plat-utils/files/sol-util
--- a/meta-facebook/meta-grandteton/meta-gtartemis/recipes-gtartemis/plat-utils/files/sol-util
+++ b/meta-facebook/meta-grandteton/meta-gtartemis/recipes-gtartemis/plat-utils/files/sol-util
@@ -25,8 +25,10 @@ readonly EXIT_ERROR=255
 usage() {
   echo "Usage: sol-util [ mb | cb | mc | cb_pesw0 | cb_pesw1 ]"
   echo "       sol-util [ cb_accl[1..12]_[1..2] ] uart[0..3] (baudrate)"
+  echo "       sol-util mc [cxl1 | cxl2 ... cxl8] (baudrate)"
+  echo "       sol-util [ mb | cb | mc ] --history"
   echo "       e.g. sol-util cb_accl1_1 uart0"
-  echo "       sol-util [ mb | cb ] --history"
+  echo "       e.g. sol-util mc cxl1"
   exit 1
 }
 
@@ -587,6 +589,63 @@ get_usb_dev() {
   echo "-s ${baudrate} ${prefix}${usb_path}"
 }
 
+get_mc_usb_dev() {
+  local usb_path=""
+  local baudrate="115200"
+  local prefix="/dev/serial/by-path/"
+  local retry=10
+  local slot="$1"
+  local comp="$2"
+
+  [ -n "$3" ] && baudrate="$3"
+
+  case $slot in
+    mc)
+      case $comp in
+        cxl1)
+          usb_path="platform-1e6a3000.usb-usb-0:1.1.3.2.3:1.0-port0"
+        ;;
+        cxl2)
+          usb_path="platform-1e6a3000.usb-usb-0:1.1.3.2.4:1.0-port0"
+        ;;
+        cxl3)
+          usb_path="platform-1e6a3000.usb-usb-0:1.1.3.2.1:1.0-port0"
+        ;;
+        cxl4)
+          usb_path="platform-1e6a3000.usb-usb-0:1.1.3.2.2:1.0-port0"
+        ;;
+        cxl5)
+          usb_path="platform-1e6a3000.usb-usb-0:1.1.3.1.4:1.0-port0"
+        ;;
+        cxl6)
+          usb_path="platform-1e6a3000.usb-usb-0:1.1.3.1.3:1.0-port0"
+        ;;
+        cxl7)
+          usb_path="platform-1e6a3000.usb-usb-0:1.1.3.1.2:1.0-port0"
+        ;;
+        cxl8)
+          usb_path="platform-1e6a3000.usb-usb-0:1.1.3.1.1:1.0-port0"
+        ;;
+        *)
+          echo "The $comp is invalid"
+          exit "$EXIT_ERROR";
+        ;;
+      esac
+    ;;
+    *)
+      echo "The $slot is invalid"
+      exit "$EXIT_ERROR";
+    ;;
+  esac
+
+  if [ "$(check_file_exist "${prefix}${usb_path}" ${retry})" = 0 ]; then
+    echo "The $usb_path is invalid"
+    exit "$EXIT_ERROR";
+  fi
+
+  echo "-s ${baudrate} ${prefix}${usb_path}"
+}
+
 SLOT=
 COMP=
 
@@ -601,6 +660,8 @@ if [ "$1" = "mb" ] || [ "$1" = "cb" ] || [ "$1" = "mc" ] || [[ "$1" =~ ^(cb_accl
     cat "$LOGFILE_B" "$LOGFILE" 2>/dev/null
     exit 0;
   elif [[ "$SLOT" =~ ^(cb_accl([1-9]|1[0-2])_(1|2))$ ]] && [[ "$2" =~ ^(uart[0-3])$ ]]; then
+    COMP=$2
+  elif [ "$SLOT" = "mc" ] && [[ "$2" =~ ^(cxl[1-8])$ ]]; then
     COMP=$2
   else
     if [ $# -ne 1 ]; then
@@ -639,6 +700,13 @@ if [ -n "$COMP" ]; then
     fi
   elif [[ "$SLOT" =~ ^(cb_pesw(0|1))$ ]]; then
     read -r PARAMETER BAUDRATE USB_PATH <<< "$(get_usb_pesw "$COMP")"
+  elif [ "$SLOT" = "mc" ]; then
+    if [[ "$COMP" =~ ^(cxl[1-8])$ ]]; then
+      read -r PARAMETER BAUDRATE USB_PATH <<< "$(get_mc_usb_dev "$SLOT" "$COMP" "$BAUDRATE")"
+    else
+      usage
+      exit "$EXIT_ERROR";
+    fi
   else
     usage
     exit "$EXIT_ERROR";
