vboot-util: Add error code text
Summary:
This adds helpful text for `vboot-util` errors.
The error type and codes are displayed in decimal, similar to the `vbs` command in U-Boot.

Test Plan:
```
root@bmc:~# vboot-util
ROM executed from:       0x00000074
ROM KEK certificates:    0x0000D250
ROM handoff marker:      0x00000000
U-Boot executed from:    0x28084350
U-Boot certificates:     0x00000000
Flags force_recovery:    0x00
Flags hardware_enforce:  0x00
Flags software_enforce:  0x00
Flags recovery_boot:     0x00
Flags recovery_retried:  0x00

Status type (3) code (35)
U-Boot FIT did not contain the /keys node
```

Reviewed By: sdasari73

fbshipit-source-id: bdfa0c0

diff --git a/meta-aspeed/recipes-utils/soc-utils/files/vboot-util b/meta-aspeed/recipes-utils/soc-utils/files/vboot-util
--- a/meta-aspeed/recipes-utils/soc-utils/files/vboot-util
+++ b/meta-aspeed/recipes-utils/soc-utils/files/vboot-util
@@ -17,6 +17,25 @@
 
 VBS="0x1E720100"
 
+ERROR[0]="OpenBMC was verified correctly"
+ERROR[10]="FMC SPI0.1 (CS1) is not populated"
+ERROR[11]="U-Boot on FMC SPI0.1 did not execute properly"
+ERROR[20]="FMC SPI0.1 (CS1) PROM status invalid or invalid read-mode"
+ERROR[30]="Invalid FDT magic number for U-Boot FIT at 0x28080000"
+ERROR[31]="U-Boot FIT did not contain the /images node"
+ERROR[32]="U-Boot FIT /images node has no 'firmware' subnode"
+ERROR[33]="U-Boot FIT did not contain the /config node"
+ERROR[34]="The ROM was not built with an embedded FDT"
+ERROR[35]="U-Boot FIT did not contain the /keys node"
+ERROR[36]="The itermediate keys within the U-Boot FIT are missing"
+ERROR[38]="U-Boot FIT total size is invalid"
+ERROR[40]="The intermediate keys could not be verified using the ROM keys"
+ERROR[41]="The intermediate keys were not verified using the ROM keys"
+ERROR[42]="U-Boot could not be verified using the intermediate keys"
+ERROR[43]="U-Boot was not verified using the intermediate keys"
+ERROR[50]="Recovery boot was forced using the force_recovery environment variable"
+ERROR[60]="The rootfs and kernel FIT is invalid"
+
 vbs_addr() {
     echo $(($VBS + $1))
 }
@@ -55,9 +74,13 @@ main() {
 
   # Errors
   ERROR_TYPE=$(devmem $(vbs_addr 0x19) 8)
+  ERROR_TYPE=$((16#${ERROR_TYPE:2:2}))
   ERROR_CODE=$(devmem $(vbs_addr 0x1A) 8)
+  ERROR_CODE=$((16#${ERROR_CODE:2:2}))
+
   echo ""
   echo "Status type ($ERROR_TYPE) code ($ERROR_CODE)"
+  test "${ERROR[$ERROR_CODE]}" && echo ${ERROR[$ERROR_CODE]} || echo "The error code is unknown"
 }
 
 main
