halt CIT test if no flash is found
Summary: currently circleci will continue to qemu cit even if previous `build` step is `halt`. This cause qemu-cit fail to run since no flash is present. We need to halt qemu-cit steps as well to prevent mis-understanding of circleci results.

Test Plan:
CircleCI: https://app.circleci.com/pipelines/github/facebookexternal/openbmc.wiwynn/6054/workflows/6f488631-cfa9-4f4a-ac9b-380a2fc41f0f

In this example, the only code change is in `meta-fby3` thus only fby3 need to go through whole CI cycle (e.g. build image + qemu-cit test). all other platforms are halt automatically.

Also add `fbtp`, `fbttn` to the qemu-cit steps as well.

Reviewed By: garnermic

fbshipit-source-id: 8ac722756a

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -105,6 +105,15 @@ jobs:
             - attach_workspace:
                 at: /tmp/job
             - run:
+                name: Check if CIT required based on flash presence
+                command: |
+                    if ! [[ -f /tmp/job/project/build/tmp/deploy/images/<< parameters.machine >>/flash-<< parameters.machine >> ]]; then
+                        echo "flash-<< parameters.machine >> not found, skip CIT"
+                        circleci-agent step halt
+                    else
+                        echo "BMC flash found, continue to CIT test"
+                    fi
+            - run:
                 name: Install Ubuntu dependencies.
                 command: |
                     apt-get update
@@ -226,4 +235,6 @@ workflows:
                             minipack,
                             wedge400,
                             yamp,
+                            fbttn,
+                            fbtp,
                             ]
