yosemite4: fw-versions: Add error handling for bic
Summary:
Description:
Add error handling for bic.

Motivation:
pldmtool doesn't return non-zero value when it fails. Add error handling so we can know if it fails to get version.

X-link: https://github.com/facebookexternal/openbmc.wiwynn/pull/3165

Test Plan:
Build code - pass
Tested on yv4 - pass

# Description

Please include a summary of the change and which issue is fixed.

# Motivation

Please include an explanation of why you these changes are necessary

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

Reviewed By: williamspatrick

Differential Revision: D62098069

fbshipit-source-id: a248169de980296aa535790d77c25dd6135aaf09

diff --git a/meta-facebook/meta-yosemite4/recipes-facebook/fw-versions/files/sd-bic b/meta-facebook/meta-yosemite4/recipes-facebook/fw-versions/files/sd-bic
--- a/meta-facebook/meta-yosemite4/recipes-facebook/fw-versions/files/sd-bic
+++ b/meta-facebook/meta-yosemite4/recipes-facebook/fw-versions/files/sd-bic
@@ -9,6 +9,11 @@ version=$(
         jq --raw-output '.ActiveComponentImageSetVersionString'
 )
 
+if [ -z "$version" ]; then
+    echo "Failed to get slot$slot sd bic version"
+    exit 1
+fi
+
 busctl set-property \
     xyz.openbmc_project.Settings \
     "/xyz/openbmc_project/software/host$slot/Sentinel_Dome_bic" \
