yosemite4: fw-versions: Revise wf-cxl for more accurate
Summary:
Description:
Revise wf-cxl to show active firmware and add timeout check for command.

Motivation:
We should be able to know the active firmware instead of showing them all. The command 'cxl-fw-update version' will hang if the CXL doesn't respond.

X-link: https://github.com/facebookexternal/openbmc.wiwynn/pull/3159

Test Plan:
Build code - pass
Tested on yv4 - pass

# Description

Please include a summary of the change and which issue is fixed.

# Motivation

Please include an explanation of why you these changes are necessary

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

Reviewed By: wangx6f

Differential Revision: D61906628

fbshipit-source-id: c7ef1087672da45d3fd7c66ee646c06c78d32a57

diff --git a/meta-facebook/meta-yosemite4/recipes-facebook/fw-versions/files/wf-cxl b/meta-facebook/meta-yosemite4/recipes-facebook/fw-versions/files/wf-cxl
--- a/meta-facebook/meta-yosemite4/recipes-facebook/fw-versions/files/wf-cxl
+++ b/meta-facebook/meta-yosemite4/recipes-facebook/fw-versions/files/wf-cxl
@@ -13,17 +13,40 @@ for pos in 1 2; do
         continue
     fi
 
-    version=$(
-        cxl-fw-update version -m $eid 2>&1 |
-        grep "Slot.*FW Revision" |
-        sed 's/.*: //' | tr '\n' ',' |
-        sed 's/,$//'
-    )
+    max_retries=3
+    retry_count=0
+    TIMEOUT_DURATION=3
 
-    busctl set-property \
-        xyz.openbmc_project.Settings \
-        "/xyz/openbmc_project/software/host$slot/Wailua_Falls_cxl_$pos" \
-        xyz.openbmc_project.Software.Version \
-        Version "s" "$version"
+    while [ $retry_count -lt $max_retries ]; do
+        # Store the output of the command in a variable
+        output=$(timeout $TIMEOUT_DURATION cxl-fw-update version -m $eid 2>&1)
+
+        # Check if the output is empty
+        if [ $? -eq 124 ]; then
+            echo "No output from cxl-fw-update. Retrying... ($((retry_count + 1))/$max_retries)"
+            retry_count=$((retry_count + 1))
+            sleep 1
+        else
+            # Extract the active slot number
+            active_slot=$(echo "$output" | grep "Active FW Slot" | awk '{print $4}')
+
+            # Extract the firmware version for the active slot
+            version=$(echo "$output" | grep "Slot $active_slot FW Revision" | sed 's/.*: //')
+
+            busctl set-property \
+                xyz.openbmc_project.Settings \
+                "/xyz/openbmc_project/software/host$slot/Wailua_Falls_cxl_$pos" \
+                xyz.openbmc_project.Software.Version \
+                Version "s" "$version"
+
+            break
+        fi
+
+    done
+
+    if [ $retry_count -eq $max_retries ]; then
+        echo "Failed to get output from cxl-fw-update after $max_retries retries on CXL$pos."
+        exit 1
+    fi
 
 done
