santabarbara: add workaround for BRCM SBR version display limitation
Summary:
# Description

BRCM FW currently only supports "ActiveComponentImageSetVersionString" to show the SBR version (displayed as fw-sbr-mfg version) instead of the PLDM-specified "ActiveComponentVersionString". This is a temporary workaround until BRCM can fix the issue.

X-link: https://github.com/facebookexternal/openbmc.quanta/pull/4894

Test Plan:
Tested on Santabarbara platform
```
root@bmc:~# mfg-tool version-display 2</dev/null | grep swb
        "swb_pcie_switch": "6.00.135.00-20a028-1.1.82.0"
```

Reviewed By: wangx6f

Differential Revision: D91469041

fbshipit-source-id: 604d41ebafc5ee95315c64efe0109b7c126a0be9

diff --git a/meta-facebook/meta-santabarbara/recipes-santabarbara/fw-versions/files/pcie-switch b/meta-facebook/meta-santabarbara/recipes-santabarbara/fw-versions/files/pcie-switch
--- a/meta-facebook/meta-santabarbara/recipes-santabarbara/fw-versions/files/pcie-switch
+++ b/meta-facebook/meta-santabarbara/recipes-santabarbara/fw-versions/files/pcie-switch
@@ -1,18 +1,42 @@
 #!/bin/bash
 
-eid=52
+source /usr/libexec/fb-common-functions
+
+rev_id_1=$(get_gpio "MB_REV_ID_1")
+rev_id_2=$(get_gpio "MB_REV_ID_2")
+
+if [ "$rev_id_1" -eq 0 ] && [ "$rev_id_2" -eq 0 ]; then
+    hub_devices=$(i2cdetect -l | grep "hub0-" | grep "\.port2")
+    target_device=$(echo "$hub_devices" | sed -n '2p')
+else
+    hub_devices=$(i2cdetect -l | grep "hub2-" | grep "\.port2")
+    target_device=$(echo "$hub_devices" | head -n 1)
+fi
+
+if [[ -z "$target_device" ]]; then
+    echo "Failed to find target device"
+    exit 1
+fi
+
+i2c_num=$(echo "$target_device" | awk '{print $1}' | cut -d'-' -f2)
+eid=$(mctp route | grep "mctpi2c$i2c_num" | grep -oE "eid min [0-9]+" | awk '{print $3}' | head -n1)
+
+if [[ -z "$eid" ]]; then
+    echo "Failed to find EID for i2c$i2c_num"
+    exit 1
+fi
+
 dbus_path="swb_pcie_switch"
 
 echo "Getting version (EID=$eid)"
 
-MAX_RETRIES=3
+MAX_RETRIES=10
 RETRY_COUNT=0
 version=""
 
 while [ "$RETRY_COUNT" -lt "$MAX_RETRIES" ]; do
     version=$(pldmtool fw_update GetFwParams -m "$eid" 2>/dev/null | \
-              jq -r '.ComponentParameterEntries[].ActiveComponentVersionString' 2>/dev/null)
-
+            jq -r '.ActiveComponentImageSetVersionString' 2>/dev/null)
     if [ -n "$version" ] && [ "$version" != "null" ]; then
         echo "Version: $version"
         
