Support random order of NVRAM indexes
Differential Revision: D4069088

fbshipit-source-id: 40ae14d

diff --git a/common/recipes-tpm/tpm-tools/files/tpm_integrationtest b/common/recipes-tpm/tpm-tools/files/tpm_integrationtest
--- a/common/recipes-tpm/tpm-tools/files/tpm_integrationtest
+++ b/common/recipes-tpm/tpm-tools/files/tpm_integrationtest
@@ -22,9 +22,10 @@ fi
 
 NVRAM_INDEXES=$(/usr/sbin/tpm_nvinfo | grep "NVRAM" | awk '{print $4}')
 EXPECTED=$(echo -e "0x30000001\n0x10000001\n0x1000f000")
-if [ "$NVRAM_INDEXES" != "$EXPECTED" ]; then
-  echo "Failed: NVRAM indexes do not match expected values"
-  echo "Expected indexes: \n$EXPECTED"
-  echo "Actual indexes: \n$NVRAM_INDEXES"
-  exit 1
-fi
+for index in $EXPECTED; do
+  FOUND=$(echo $NVRAM_INDEXES | grep $index)
+  if [ "$FOUND" == "" ]; then
+    echo "Failed: Cannot find NVRAM index: $index"
+    exit 1
+  fi
+done
