vboot2,sign: update the helper vboot-sign script to support use HSM sign
Summary: as title

Test Plan:
* extract the all signing contents (kek and signed subordinated blobs)
```
[ ~/openbmc/build-fby3] ../tools/verified-boot/signing/vboot-sign -s -k ~/workspaces/obmc-ks/hsm -S compute
POKY_BUILD=/home/zhdaniel/openbmc/build-fby3
POKY_DIR=/home/zhdaniel/openbmc
KEYS_DIR=/home/zhdaniel/workspaces/obmc-ks/hsm
IMAGE_NAME=fby3
find mkimage in u-boot-tools-native
~/openbmc/tools/verified-boot/signing ~/openbmc/build-fby3
Setup signing content for HSM in /home/zhdaniel/workspaces/obmc-ks/hsm
~/workspaces/obmc-ks/hsm ~/openbmc/tools/verified-boot/signing ~/openbmc/build-fby3
Archive:  ks.zip
  inflating: kek.dtb.compute
  inflating: kek.dtb.network
  inflating: kek.dtb.storage
  inflating: kek.dtb.training
  inflating: README
  inflating: subordinate.dtb.signed.compute
  inflating: subordinate.dtb.signed.network
  inflating: subordinate.dtb.signed.storage
  inflating: subordinate.dtb.signed.training
~/openbmc/tools/verified-boot/signing ~/openbmc/build-fby3
Keys are generated in /home/zhdaniel/workspaces/obmc-ks/hsm
[ ~/openbmc/build-fby3] tree ~/workspaces/obmc-ks/hsm
~/workspaces/obmc-ks/hsm
├── kek.dtb.compute
├── kek.dtb.network
├── kek.dtb.storage
├── kek.dtb.training
├── README
├── subordinate.dtb.signed.compute
├── subordinate.dtb.signed.network
├── subordinate.dtb.signed.storage
└── subordinate.dtb.signed.training

0 directories, 9 files

```

* local (on dev-server) sign "compute" platforms' OpenBMC image with hsm kek and signed subordinated blob extracted in ~/workspaces/obmc-ks/hsm, within the build folder build-fby3, after build fby3 image successfully.

```
[~/workspaces/openbmc/build-fby3] ../tools/verified-boot/signing/vboot-sign -k ~/workspaces/obmc-ks/hsm -S compute

...

  Timestamp:    Tue Oct 13 00:30:59 2020
Wrote signed firmware: /data/users/zhdaniel/workspaces/openbmc/build-fby3/tmp/deploy/images/fby3/flash-fby3.signed

```

* signing out-of-tree image
```
[ ~/release/fby3/hsm-test/hsm-rb] ~/openbmc/tools/verified-boot/signing/vboot-sign \
  -b ~/openbmc/build-fby3 \
  -k ~/workspaces/obmc-ks/hsm/
  -S compute \
  -i ./flash-fby3

```

Reviewed By: benwei13

fbshipit-source-id: 3ea96b54bb

diff --git a/tools/verified-boot/signing/vboot-sign b/tools/verified-boot/signing/vboot-sign
--- a/tools/verified-boot/signing/vboot-sign
+++ b/tools/verified-boot/signing/vboot-sign
@@ -12,6 +12,7 @@ POKY_BUILD=`pwd`
 KEYS=$(realpath $(dirname "$0"))
 SETUP=NO
 HELP=NO
+PLATFORM_TYPE=""
 
 PYTHON=/usr/local/bin/python
 if [ ! -x $PYTHON ]; then
@@ -42,6 +43,10 @@ case $key in
     -s|--setup)
     SETUP=YES
     ;;
+    -S|--HSM)
+    PLATFORM_TYPE=${2}
+    shift
+    ;;
     --help)
     HELP=YES
     ;;
@@ -63,24 +68,28 @@ if [ "$HELP" == "YES" ]; then
   echo "    Set the build directory to BUILD_DIR. Else the current working directory will be used"
   echo "-s|--setup"
   echo "    Generate the keys in KEYS_DIR (See above for default path)"
+  echo "-S|--HSM {compute|storage|network|training}"
+  echo "    Use FB HSM keyname ncipher/simple/obmc-<platform_type>-sub-0 key to sign"
   exit 0
 fi
 
 POKY_DIR=$(dirname $POKY_BUILD)
 SIGN_SCRIPT_HOME=$POKY_DIR/tools/verified-boot/signing
-CURRENT_DIR=`pwd`
 IMAGES_DIR=$POKY_BUILD/tmp/deploy/images
-if [ ! -d $IMAGES_DIR ]; then
+
+if [ ! -d "$IMAGES_DIR" ]; then
   echo "$POKY_BUILD is not a valid build directory!"
-  exit -1
+  exit 255
 fi
-IMAGE_NAME=$(ls $IMAGES_DIR)
+IMAGE_NAME=$(ls "$IMAGES_DIR")
 if [ "$IMAGE_NAME" == "" ]; then
   echo "Could not find any images in $IMAGE_DIR"
-  exit -1;
+  exit 255
 fi
 if [ "$IMAGE_PATH" == "" ]; then
   IMAGE_PATH=$POKY_BUILD/tmp/deploy/images/$IMAGE_NAME/flash-${IMAGE_NAME}
+else
+  IMAGE_PATH=$(realpath "$IMAGE_PATH")
 fi
 echo "POKY_BUILD=$POKY_BUILD"
 echo "POKY_DIR=$POKY_DIR"
@@ -89,52 +98,70 @@ echo "IMAGE_NAME=$IMAGE_NAME"
 
 MKIMAGE=$POKY_BUILD/tmp/sysroots/x86_64-linux/usr/bin/mkimage
 # Location is different for rocko
-if [ ! -x $MKIMAGE ]; then
+if [ ! -x "$MKIMAGE" ]; then
   MKIMAGE=$POKY_BUILD/tmp/sysroots-components/x86_64/u-boot-mkimage-native/usr/bin/mkimage
-  export LD_LIBRARY_PATH=$POKY_BUILD/tmp/sysroots-components/x86_64/openssl-native/usr/lib:$LD_LIBRARY_PATH
 fi
-if [ ! -x $MKIMAGE ]; then
+# Location is different for u-boot-tools
+if [ ! -x "$MKIMAGE" ]; then
+  echo "find mkimage in u-boot-tools-native"
+  MKIMAGE=$POKY_BUILD/tmp/sysroots-components/x86_64/u-boot-tools-native/usr/bin/mkimage
+fi
+
+if [ ! -x "$MKIMAGE" ]; then
+  echo "$MKIMAGE"
   echo "mkimage could not be found in build directory!"
   echo "Probably $POKY_BUILD is not a build directory?"
-  exit -1
+  exit 255
 fi
 
-cd $SIGN_SCRIPT_HOME
+pushd "$SIGN_SCRIPT_HOME" || { echo "change PWD to $SIGN_SCRIPT_HOME fail"; exit 1; }
 
 if [ "$SETUP" == "YES" ]; then
-  if [ ! -d $KEYS ]; then
-    mkdir $KEYS
+  mkdir -p "$KEYS"
+  if [ -n "$PLATFORM_TYPE" ]; then
+    echo "Setup signing content for HSM in $KEYS"
+    pushd "$KEYS" || { echo "switch CWD to $KEYS failed"; exit 1; }
+      secrets_tool get_from_group --out_file ks.zip SIGNING_CONTENT OPENBMC_VBOOT2_KS && unzip ks.zip && rm ks.zip
+    popd
+  else
+    echo "Setup signing content in $KEYS"
+    mkdir -p "$KEYS/kek"
+    mkdir -p "$KEYS/subordinate"
+    openssl genrsa -F4 -out "$KEYS/kek/kek.key" 4096
+    openssl rsa -in "$KEYS/kek/kek.key" -pubout > "$KEYS/kek/kek.pub"
+    openssl genrsa -F4 -out "$KEYS/subordinate/subordinate.key" 4096
+    openssl rsa -in "$KEYS/subordinate/subordinate.key" -pubout > "$KEYS/subordinate/subordinate.pub"
+    $PYTHON ./fit-cs --template ./store.dts.in "$KEYS/kek" "$KEYS/kek/kek.dtb"
+    $PYTHON ./fit-cs --template ./store.dts.in --subordinate --subtemplate ./sub.dts.in \
+      "$KEYS/subordinate" "$KEYS/subordinate/subordinate.dtb"
+    LD_LIBRARY_PATH=$POKY_BUILD/tmp/sysroots-components/x86_64/openssl-native/usr/lib:$LD_LIBRARY_PATH \
+    $PYTHON ./fit-signsub --keydir "$KEYS/kek" --mkimage "$MKIMAGE" \
+      "$KEYS/subordinate/subordinate.dtb" "$KEYS/subordinate/subordinate.dtb.signed"
   fi
-  if [ ! -d $KEYS/kek ]; then
-    mkdir $KEYS/kek
-  fi
-  if [ ! -d $KEYS/subordinate ]; then
-    mkdir $KEYS/subordinate
-  fi
-  openssl genrsa -F4 -out $KEYS/kek/kek.key 4096
-  openssl rsa -in $KEYS/kek/kek.key -pubout > $KEYS/kek/kek.pub
-  openssl genrsa -F4 -out $KEYS/subordinate/subordinate.key 4096
-  openssl rsa -in $KEYS/subordinate/subordinate.key -pubout > $KEYS/subordinate/subordinate.pub
-  $PYTHON ./fit-cs --template ./store.dts.in $KEYS/kek $KEYS/kek/kek.dtb
-  $PYTHON ./fit-cs --template ./store.dts.in --subordinate --subtemplate ./sub.dts.in $KEYS/subordinate $KEYS/subordinate/subordinate.dtb
-  $PYTHON ./fit-signsub --mkimage $MKIMAGE --keydir $KEYS/kek $KEYS/subordinate/subordinate.dtb $KEYS/subordinate/subordinate.dtb.signed
+
   echo "Keys are generated in $KEYS"
   exit 0
 fi
 
-if [ ! -d $KEYS ]; then
+if [ ! -d "$KEYS" ]; then
   echo "keys directory $KEYS does not exist!"
-  exit -1
+  exit 255
 fi
 
-$PYTHON ./fit-sign --mkimage $MKIMAGE \
-                  --kek $KEYS/kek/kek.dtb \
-                  --signed-subordinate $KEYS/subordinate/subordinate.dtb.signed \
-                  --keydir $KEYS/subordinate \
+if [ -n "$PLATFORM_TYPE" ]; then
+  SIGNKEY="--keyname ncipher/simple/obmc-${PLATFORM_TYPE}-sub-0"
+else
+  SIGNKEY="--keydir $KEYS/subordinate"
+fi
+
+LD_LIBRARY_PATH=$POKY_BUILD/tmp/sysroots-components/x86_64/openssl-native/usr/lib:$LD_LIBRARY_PATH \
+$PYTHON ./fit-sign $SIGNKEY \
+                  --mkimage "$MKIMAGE" \
+                  --kek "$KEYS/kek.dtb.${PLATFORM_TYPE}" \
+                  --signed-subordinate "$KEYS/subordinate.dtb.signed.${PLATFORM_TYPE}" \
                   --sign-os \
-                  $IMAGE_PATH \
-                  ${IMAGE_PATH}.signed
+                  "$IMAGE_PATH" \
+                  "${IMAGE_PATH}.signed"
+
 # Go back
-cd $CURRENT_DIR
-
-
+popd
