Fix Clemente CPLD and PDB board support.
Summary:
# Description
Update the fw-versions and fw-util recipes to support Clemente machine.
- Enable support for two HDDs on the CPLD.
- Remove the VR-AUX device from the PDB.

# Motivation
- The Clemente machine does not support the VR-AUX device and requires support for two HDDs.

X-link: https://github.com/facebookexternal/openbmc.ingrasys/pull/11

Test Plan:
Test command :

1.
busctl tree xyz.openbmc_project.Settings
```
    | `- /xyz/openbmc_project/software/chassis
    |   |- /xyz/openbmc_project/software/chassis/Clemente_HDD_cpld_0
    |   |- /xyz/openbmc_project/software/chassis/Clemente_HDD_cpld_1
    |   |- /xyz/openbmc_project/software/chassis/Clemente_PDB_cpld
    |   |- /xyz/openbmc_project/software/chassis/Clemente_PDB_vr_n1
    |   |- /xyz/openbmc_project/software/chassis/Clemente_PDB_vr_n2
    |   |- /xyz/openbmc_project/software/chassis/Clemente_SCM_cpld
    |   |- /xyz/openbmc_project/software/chassis/Clemente_SCM_tpm
```

2.
busctl get-property xyz.openbmc_project.Settings /xyz/openbmc_project/software/chassis/Clemente_HDD_cpld_0 xyz.openbmc_project.Software.Version Version

and

busctl get-property xyz.openbmc_project.Settings /xyz/openbmc_project/software/chassis/Clemente_HDD_cpld_1 xyz.openbmc_project.Software.Version Version

`s "000B0402"`

3.
fw-util
```
USAGE: fw-util all|FRU --version|--version-json [all|COMPONENT]
       fw-util FRU --update [--]COMPONENT IMAGE_PATH
       fw-util FRU --force --update [--]COMPONENT IMAGE_PATH
       fw-util FRU --dump [--]COMPONENT IMAGE_PATH
       fw-util FRU --update COMPONENT IMAGE_PATH --schedule now
       fw-util all --show-schedule
       fw-util all --delete-schedule TASK_ID

FRU        : Components
---------- : ----------
bmc        : tpm
hdd0       : cpld
hdd1       : cpld
hmc        : bundle sbios
nic0       : nic0
nic1       : nic1
pdb        : cpld vr_n1 vr_n2
scm        : cpld
```

fw-util all --version
```
TPM Version: 15.23
HDD0_CPLD Version: 000B0402
HDD1_CPLD Version: 000B0402
HGX_FW_BMC_0: GB200Nvl-25.05-3
...
```

fw-util hdd0 --update cpld /tmp/NV_S8B_0B_04_02.jed
```
Device ID : 012BC043
[ChkSUM]85ed
erase command : 0E 04 00 00
updated cpld: 100 %
read user code:
00 0B 04 02
verify cpld: 100 %
Sending exit program mode cmd
Sending bypass instruction cmd
Upgrade of hdd0 : cpld succeeded

```

fw-util hdd1 --update cpld /tmp/NV_S8B_0B_04_02.jed
```
Device ID : 012BC043
[ChkSUM]85ed
erase command : 0E 04 00 00
updated cpld: 100 %
read user code:
00 0B 04 02
verify cpld: 100 %
Sending exit program mode cmd
Sending bypass instruction cmd
Upgrade of hdd1 : cpld succeeded
```

Reviewed By: ifel

Differential Revision: D76968054

fbshipit-source-id: 31e506e7e2c314bf2e6983dce5a7220e6f62417a

diff --git a/meta-facebook/meta-catalina/recipes-catalina/fw-versions/files/clemente/hdd-cpld b/meta-facebook/meta-catalina/recipes-catalina/fw-versions/files/clemente/hdd-cpld
--- a/meta-facebook/meta-catalina/recipes-catalina/fw-versions/files/clemente/hdd-cpld
+++ b/meta-facebook/meta-catalina/recipes-catalina/fw-versions/files/clemente/hdd-cpld
@@ -1,11 +1,17 @@
 #!/bin/bash
 set -e
 
-version=$(fw-util hdd --version cpld | awk '{print $NF}')
+if [ -z "$1" ]; then
+    echo "Error: No instances parameter provided."
+    exit 1
+fi
+
+instances=$1
+version=$(fw-util "hdd${instances}" --version cpld | awk '{print $NF}')
 echo "version: $version"
 
 busctl set-property \
     xyz.openbmc_project.Settings \
-    /xyz/openbmc_project/software/chassis/Clemente_HDD_cpld \
+    "/xyz/openbmc_project/software/chassis/Clemente_HDD_cpld_${instances}" \
     xyz.openbmc_project.Software.Version \
     Version "s" "$version"
