halfdome: add fan config for halfdome (#3057)
Summary:
halfdome: add fan config for halfdome and set to fixed fan speed 80 pwm

X-link: https://github.com/facebookexternal/openbmc.quanta/pull/3057

Test Plan:
1. check fan config switch to halfdome fan config
root@bmc-oob:~# fw-util bmc --version fscd
Fan Speed Controller Version: halfdome-v2022.07.11
2. Fan speed fixed to 80 pwm
root@bmc-oob:~# fan-util --get
Fan 0 Speed: 8491 RPM (80%)
Fan 1 Speed: 8541 RPM (80%)
Fan 2 Speed: 8516 RPM (80%)
Fan 3 Speed: 8616 RPM (80%)
Fan Mode: Normal
FSCD Driver: linear_frontIO_inlet(slot1:fio_temp)
Sensor Fail: None
Fan Fail: None

Reviewed By: amithash

fbshipit-source-id: 67bd63bdae1737933a887d71fa57fc5d97c6864f

diff --git a/meta-facebook/meta-fby35/recipes-fby35/plat-utils/files/ast-functions b/meta-facebook/meta-fby35/recipes-fby35/plat-utils/files/ast-functions
--- a/meta-facebook/meta-fby35/recipes-fby35/plat-utils/files/ast-functions
+++ b/meta-facebook/meta-fby35/recipes-fby35/plat-utils/files/ast-functions
@@ -225,11 +225,21 @@ get_slot_type() {
   echo $type
 }
 
-# Get server type. 0 = server
+# Get server type
+# Crater Lake: 0x00
+# Halfdome: 0x02
+# unknown type: 0xff
 get_server_type() {
-  #Return 0 since we only have a server
-  type=0
-  echo $type
+  #local bus=$1
+  local bus=$(get_cpld_bus "$1")
+  SB_CPLD_ADDR="0x0f"
+  type=$(/usr/sbin/i2cget -y $bus $SB_CPLD_ADDR 0x11)
+  if [ $? -ne 0 ]; then
+    # if get server type fail, return unknown server for retry or search other slot's server
+    echo "0xff"
+  else
+    echo $type
+  fi
 }
 
 # Check to see if Bridge-IC is ready
