fby35: support bb bic recovery (#2069)
Summary:
Support BB BIC recovery and adjust the command format.

X-link: https://github.com/facebookexternal/openbmc.wiwynn/pull/2069

Test Plan:
Build and test pass on fby35 system.
1. BB BIC recovery
root@bmc-oob:~# recovery-bic-util slot1 -f bb uart_Y35BBB_2099.bin Y35BBB_2022.bin
Setting slot UART to SB BIC
Could not get the server board index, please enter the slot number manually (1 or 3)
1
Setting BIC boot from UART
Doing the recovery update...
Executing the fw-util for updating bic...
slot_id: 1, comp: d, intf: 0, img: Y35BBB_2022.bin, force: 1
Set fan mode to manual and set PWM to 70%
file size = 260312 bytes, slot = 1, intf = 0x10
updating fw on slot 1:
updated bic: 100 %
Elapsed time:  28   sec.

Set fan mode to auto and start fscd
Force upgrade of slot1 : bb_bic succeeded
Power-cycling the server...
root@bmc-oob:~# fw-util slot1 --version bb_bic
BB Bridge-IC Version: oby35-bb-v2022.01.01

Reviewed By: GoldenBug

fbshipit-source-id: 36878efb389de75559c18c79a61fbcf544092e09

diff --git a/meta-facebook/meta-fby35/recipes-fby35/plat-utils/files/recovery-bic-util b/meta-facebook/meta-fby35/recipes-fby35/plat-utils/files/recovery-bic-util
--- a/meta-facebook/meta-fby35/recipes-fby35/plat-utils/files/recovery-bic-util
+++ b/meta-facebook/meta-fby35/recipes-fby35/plat-utils/files/recovery-bic-util
@@ -23,20 +23,20 @@ SLED_TYPE="/mnt/data/kv_store/sled_system_conf"
 I2CSET="/usr/sbin/i2cset -y "
 
 SB_CPLD_ADDR="0x0f"
-BOARD_ID=$(get_bmc_board_id)
+BB_CPLD_ADDR="0x0e"
 
 SLOT=
 SLOT_NUM=
 I2C_NUM=
 
-function show_usage() {
-  echo "Usage: recovery-bic-util [ slot1 | slot2 | slot3 | slot4 ] [-f] <uart image path> <ipmb image path>"
+show_usage() {
+  echo "Usage: recovery-bic-util [ slot1 | slot2 | slot3 | slot4 ] [-f] [ sb | bb ] <uart image path> <ipmb image path>"
   echo "-f : forced update"
-  echo "Recovery update for server board BIC"
+  echo "Recovery update for BIC"
   echo ""
 }
 
-function get_slot_num() {
+get_slot_num() {
   local slot_num=0
   case $1 in
     slot1)
@@ -56,7 +56,7 @@ function get_slot_num() {
   echo $slot_num
 }
 
-function get_bus_num() {
+get_bus_num() {
   local bus=0
   case $1 in
     slot1)
@@ -76,85 +76,161 @@ function get_bus_num() {
   echo $bus
 }
 
-function set_cpld_reg() {
+set_cpld_reg() {
   local bus=$1
   local addr=$2
   local data=$3
-  $I2CSET $bus $addr $data
+  $I2CSET "$bus" "$addr" "$data"
+  # Add delay to avoid timing issue
+  sleep 1
 }
 
-if [ $# -gt 5 ]; then
+if [ $# -gt 6 ]; then
     show_usage
-    exit -1;
+    exit 255
+fi
+
+if [ "$2" = "-f" ] ; then
+  force=true
+  if [ "$3" = "bb" ] ; then
+    component="bb_bic"
+  elif [ "$3" = "sb" ] ; then
+    component="bic"
+  else
+    echo "Component $component not supported"
+    show_usage
+    exit 255
+  fi
+  uart_image="$4"
+  i2c_image="$5"
+else
+  force=flase
+  if [ "$2" = "bb" ] ; then
+    component="bb_bic"
+  elif [ "$2" = "sb" ] ; then
+    component="bic"
+  else
+    echo "Component $component not supported"
+    show_usage
+    exit 255
+  fi
+  uart_image="$3"
+  i2c_image="$4"
+fi
+
+if [ -z "$uart_image" ]; then
+  echo "Please provide UART image"
+  show_usage
+  exit 255
+elif [ -z "$i2c_image" ]; then
+  echo "Please provide I2C image"
+  show_usage
+  exit 255
 fi
 
 # Only support slot[1|2|3|4]
-if [[ "$1" =~ ^(slot[1-4]{1})$ ]]; then
+if [ "$1" =~ ^(slot[1-4]{1})$ ]; then
   SLOT=$1
 else
   show_usage
-  exit -1;
+  exit 255
 fi
 
-SLOT_NUM=$(get_slot_num $SLOT)
-I2C_NUM=$(get_bus_num $SLOT)
-SLED_TYPE=$(cat $SLED_TYPE)
-CPLD_ADDR=
+SLOT_NUM=$(get_slot_num "$SLOT")
+I2C_NUM=$(get_bus_num "$SLOT")
+SLED_TYPE=$(cat "$SLED_TYPE")
 
 # Set slot UART to SB BIC
 echo "Setting slot UART to SB BIC"
-if [[ "$SLED_TYPE" =~ ^(Type_(8|17))$ ]]; then
-  if ! [ "$SLOT" == "slot1" ]; then
+if [ "$SLED_TYPE" =~ ^(Type_(8|17))$ ]; then
+  if ! [ "$SLOT" = "slot1" ]; then
     echo "$SLOT is empty"
-    exit -1;
+    exit 255
   else
     # notify CPLD to set the uart src to class 2
-    set_cpld_reg $I2C_NUM $SB_CPLD_ADDR "0x00 0x02"
+    set_cpld_reg "$I2C_NUM" "$SB_CPLD_ADDR" "0x00 0x02"
   fi
 else
-  if [ $(is_server_prsnt ${SLOT_NUM}) == "0" ]; then
+  if [ "$(is_server_prsnt "${SLOT_NUM}")" = "0" ]; then
     echo "The $SLOT is empty"
-    exit -1;
-  elif [ $(is_slot_12v_on ${SLOT_NUM}) == "0" ]; then
+    exit 255
+  elif [ "$(is_slot_12v_on "${SLOT_NUM}")" = "0" ]; then
     echo "The $SLOT is 12V-off"
-    exit -1;
+    exit 255
   else
     # notify CPLD to set the uart src to class 1
-    set_cpld_reg $I2C_NUM $SB_CPLD_ADDR "0x00 0x01"
+    set_cpld_reg "$I2C_NUM" "$SB_CPLD_ADDR" "0x00 0x01"
   fi
 fi
-set_cpld_reg $I2C_NUM $SB_CPLD_ADDR "0x01 0x03"
+
+# Switch UART to corresponding BIC
+if [ "$component" = "bb_bic" ]; then
+  set_cpld_reg "$I2C_NUM" "$SB_CPLD_ADDR" "0x01 0x04"
+else
+  set_cpld_reg "$I2C_NUM" "$SB_CPLD_ADDR" "0x01 0x03"
+fi
+
+if [ "$component" = "bb_bic" ]; then
+  mb_index=$(/usr/bin/bic-util slot1 0xe0 0x2 0x9c 0x9c 0x0 0x10 0xc0 0xf0 | awk '{print $NF}')
+  if [ "$mb_index" = "01" ]; then
+    set_cpld_reg "$I2C_NUM" "$BB_CPLD_ADDR" "0x29 0x01" #slot1
+  elif [ "$mb_index" = "03" ]; then
+    set_cpld_reg "$I2C_NUM" "$BB_CPLD_ADDR" "0x29 0x02" #slot3
+  else
+    echo "Could not get the server board index, please enter the slot number manually (1 or 3)"
+    read -r slot_num
+    if [ "$slot_num" = "1" ]; then
+      set_cpld_reg "$I2C_NUM" "$BB_CPLD_ADDR" "0x29 0x01"
+    elif [ "$slot_num" = "3" ]; then
+      set_cpld_reg "$I2C_NUM" "$BB_CPLD_ADDR" "0x29 0x02"
+    else
+      echo "Invalid slot number $slot_num, please type 1 or 3."
+      exit 255
+    fi
+  fi
+fi
 
 # Set BIC boot from UART
 echo "Setting BIC boot from UART"
-set_cpld_reg $I2C_NUM $SB_CPLD_ADDR "0x10 0x01"
+if [ "$component" = "bb_bic" ]; then
+  set_cpld_reg "$I2C_NUM" "$BB_CPLD_ADDR" "0x28 0x01"
+else
+  set_cpld_reg "$I2C_NUM" "$SB_CPLD_ADDR" "0x10 0x01"
+fi
 
 # set UART to 115200
-/bin/stty -F /dev/ttyS$SLOT_NUM 115200
+/bin/stty -F "/dev/ttyS$SLOT_NUM" 115200
 echo "Doing the recovery update..."
-if [ "$2" == "-f" ] ; then
-  cat $3 > /dev/ttyS$SLOT_NUM
-else
-  cat $2 > /dev/ttyS$SLOT_NUM
-fi
+
+cat "$uart_image" > "/dev/ttyS$SLOT_NUM"
 
 sleep 5
 
 # set UART back to 57600
-/bin/stty -F /dev/ttyS$SLOT_NUM 57600
+/bin/stty -F "/dev/ttyS$SLOT_NUM" 57600
+
 echo "Executing the fw-util for updating bic..."
-if [ "$2" == "-f" ] ; then
-  /usr/bin/fw-util slot$SLOT_NUM --force --update bic $4
+if [ $force = true ] ; then
+  /usr/bin/fw-util "slot$SLOT_NUM" --force --update "$component $i2c_image"
 else
-  /usr/bin/fw-util slot$SLOT_NUM --update bic $3
+  /usr/bin/fw-util "slot$SLOT_NUM" --update "$component $i2c_image"
 fi
 
 # Set BIC boot from spi
-set_cpld_reg $I2C_NUM $SB_CPLD_ADDR "0x10 0x00"
+if [ "$component" = "bb_bic" ]; then
+  set_cpld_reg "$I2C_NUM" "$BB_CPLD_ADDR" "0x28 0x00"
+else
+  set_cpld_reg "$I2C_NUM" "$SB_CPLD_ADDR" "0x10 0x00"
+fi
+
 echo "Power-cycling the server..."
-/usr/local/bin/power-util slot$SLOT_NUM 12V-cycle
+if [ "$component" = "bb_bic" ]; then
+  /usr/local/bin/power-util sled-cycle
+else
+  /usr/local/bin/power-util "slot$SLOT_NUM" 12V-cycle
+fi
 
 echo
 echo "------------------------------------"
-echo "Recovery SB BIC is finished!"
+echo "Recovery BIC is finished!"
 echo
