Stop CircleCI Lint from Exit on First Error.
Summary:
Currently CircleCI lint operation exits on the first linting error that
it finds. However this means that when a PR contains multiple files with
lint errors, the creator would need to fix the first ones identified
before the others will be reported. Preferably all linting errors would
be reported at once so that they can all be fixed.

Test Plan:
With Errors:
```
[~/local/openbmc] ./tools/circle-ci/do-lint
CPPC: lint_errors_cppcheck.c
Checking lint_errors_cppcheck.c ...
[lint_errors_cppcheck.c:3]: (style) Variable 'x' is not assigned a value.
[lint_errors_cppcheck.c:7]: (error) Address of an auto-variable returned.
[lint_errors_cppcheck.c:4]: (error) Uninitialized variable: x
PY: lint_errors_python.py
 --- lint_errors_python.py	2021-03-22 21:32:58.711270 +0000
+++ lint_errors_python.py	2021-03-22 22:37:31.997904 +0000
@@ -1,6 +1,5 @@
-
 a = 23
 b = 45
 c = a + b

-print(c);
+print(c)
would reformat lint_errors_python.py
Oh no! � � �
1 file would be reformatted.
SH: tools/circle-ci/do-lint
FAIL : 2 files failed linting.
[~/local/openbmc] echo $?
1
```

Without Errors:
```

[~/local/openbmc] ./tools/circle-ci/do-lint
SH: tools/circle-ci/do-lint
PASS
[~/local/openbmc] echo $?
0
```

Reviewed By: benwei13

fbshipit-source-id: 3c560ecb25

diff --git a/tools/circle-ci/do-lint b/tools/circle-ci/do-lint
--- a/tools/circle-ci/do-lint
+++ b/tools/circle-ci/do-lint
@@ -1,5 +1,12 @@
 #!/bin/bash
-set -e
+
+# Count errors and don't exit early
+errors=0
+CountErrorsHandler () {
+  (( errors++ ))
+}
+
+trap CountErrorsHandler ERR
 
 # Try to use the black executable, it it does not
 # exist, try the python module.
@@ -52,7 +59,6 @@ ORIGIN_COMMIT="$(git merge-base HEAD origin/helium 2>/dev/null || git merge-base
 
 MODIFIED_FILES="$(git diff --diff-filter=d --name-only "$ORIGIN_COMMIT" --)"
 
-
 for f in $MODIFIED_FILES; do
   if [[ "$f" =~ .*\.sh$ ]]; then
     do_lint_sh "$f"
@@ -60,7 +66,7 @@ for f in $MODIFIED_FILES; do
   elif is_c_family_file "$f"; then
     do_lint_cppcheck "$f"
  elif [[ "$f" =~ .*\.py$ ]]; then
-    do_lint_py "$f"
+   do_lint_py "$f"
   else
     first=$(head -1 "$f")
     if [[ "$first" =~ \#!/.*/sh  || "$first" =~ \#!/.*/bash ]]; then
@@ -72,4 +78,10 @@ for f in $MODIFIED_FILES; do
     fi
   fi
 done
-echo "PASS"
+
+if [ "$errors" -ne 0 ]; then
+  echo "FAIL : $errors files failed linting."
+  exit 1
+else
+  echo "PASS"
+fi
